pipeline{
    agent any
    stages{
        stage('sonar'){
            // agent{
                // docker{
                //     image 'maven'
                //     args '-v $HOME/.m2:/root/.m2'
                // }
            // }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-secret') {
                        sh 'cd cicd-project3 && mvn sonar:sonar'
                    }

                   
                }
            }
        }
    }
}