pipeline{
    agent none
    stages{
        stage('sonar'){
            agent{
                docker{
                    image 'maven'
                }
            }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-secret') {
                        sh 'cd cicd-project3 && mvn sonar:sonar'
                    }

                   
                }
            }
        }
    }
}