apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jaav-deploy
  labels:
    app: java
spec:
  selector:
    matchLabels:
      app: java
  replicas: 2
  template:
    metadata: 
      labels:
        app: java
    spec:
      containers:
        - name: first-deploy-java
          image:  pardiuman/javafile:1.0
          ports: 
            - containerPort: 9099


--- 

apiVersion: v1
kind: Service
metadata: 
  name: java-app-service
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 8080
      nodePort: 30001
  type: NodePort
