pipeline{
    agent none
    // parameters{
    //     string(name: 'DOCKER', defaultValue: 'JAVA-PROGRAM', description: '')
    // }
    environment{
        DOCKER_CREDS = credentials('docker-cred')
        BUILD = "$env.BUILD_NUMBER"
        
    }
    stages{
        stage('project build'){
            agent{
                docker{
                    image 'maven'
                    args '--user root'
                }
            }
            steps{
                dir('cicd-project'){
                    sh 'mvn clean install'
                }
                
            }

        }
        stage('send dockerfile to ansible server'){

            agent any

            // environment{
            //     DOCKERFILE_NAME = "$params.DOCKER"
            // }
            
            steps{
                sshagent(['ssh-ansible']) {
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44'
                    sh 'scp -r /var/lib/jenkins/workspace/project/cicd-project/* ubuntu@34.204.5.44:/home/ubuntu/'
                }
            }
        }

        stage('build dockerfile and push'){
            agent any
            steps{
                sshagent(['ssh-ansible']){
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 cd /home/ubuntu/
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 docker build -t javafile:$BUILD_NUMBER .
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 docker tag javafile:$BUILD_NUMBER $DOCKER_CREDS_USR/javafile:$BUILD_NUMBER 
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 docker tag javafile:$BUILD_NUMBER $DOCKER_CREDS_USR/javafile:latest
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 docker login -u $DOCKER_CREDS_USR -p $DOCKER_CREDS_PSW
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 docker push $DOCKER_CREDS_USR/javafile:$BUILD_NUMBER
                        ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 docker push $DOCKER_CREDS_USR/javafile:latest
                    '''
                }
            }
        }

        stage('copy manifests file to ansible server'){
            agent any
            steps{
                sshagent(['ssh-ansible']){

                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 cd /home/ubuntu/'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 echo $PATH'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 which ansible-playbook'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 ansible --version'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 cp /home/ubuntu/kubernetes/* /home/ubuntu/'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@34.204.5.44 /usr/bin/ansible-playbook ansible-deploy.yml -i inv'

                }           
            }
        }
    } 
}