pipeline{
    agent none
    // parameters{
    //     string(name: 'DOCKER', defaultValue: 'JAVA-PROGRAM', description: '')
    // }
    environment{
        DOCKER_CREDS = credentials('docker-cred')
        BUILD = "$env.BUILD_NUMBER"
        
    }
    stages{
        stage('project build'){
            agent{
                docker{
                    image 'maven'
                    args '--user root'
                }
            }
            steps{
                dir('cicd-project'){
                    sh 'mvn clean install'
                }
                
            }

        }
        stage('send dockerfile to ansible server'){

            agent any

            // environment{
            //     DOCKERFILE_NAME = "$params.DOCKER"
            // }
            
            steps{
                sshagent(['ssh-ansible']) {
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@3.95.19.37'
                    sh 'scp -r /var/lib/jenkins/workspace/project/cicd-project/ ubuntu@3.95.19.37:/home/ubuntu/app/'
                    // sh 'ssh -o StrictHostKeyChecking=no ubuntu@3.95.19.37 cd /home/ubuntu/app/'
                    // sh 'ssh -o StrictHostKeyChecking=no ubuntu@3.95.19.37 docker build -f /home/ubuntu/app/ -t $DOCKER_CREDS_USR/javafile:1 '
                }
            }
        }
    }
}